const product1 = {
  TileID: 0,
  Stockcode: 48824,
  Barcode: '5740200001012',
  GtinFormat: 13,
  CupPrice: 50,
  InstoreCupPrice: 50,
  CupMeasure: '1KG',
  CupString: '$50.00 / 1KG',
  InstoreCupString: '$50.00 / 1KG',
  HasCupPrice: true,
  InstoreHasCupPrice: true,
  Price: 7.5,
  InstorePrice: 7.5,
  Name: 'Castello Blue Cheese Creamy',
  DisplayName: 'Castello Blue Cheese Creamy 150g',
  UrlFriendlyName: 'castello-blue-cheese-creamy',
  Description: ' Castello Blue Cheese Creamy 150G',
  SmallImageFile: 'https://cdn1.woolworths.media/content/wowproductimages/small/048824.jpg',
  MediumImageFile: 'https://cdn1.woolworths.media/content/wowproductimages/medium/048824.jpg',
  LargeImageFile: 'https://cdn1.woolworths.media/content/wowproductimages/large/048824.jpg',
  IsNew: false,
  IsHalfPrice: false,
  IsOnlineOnly: false,
  IsOnSpecial: false,
  InstoreIsOnSpecial: false,
  IsEdrSpecial: false,
  SavingsAmount: 0,
  InstoreSavingsAmount: 0,
  WasPrice: 7.5,
  InstoreWasPrice: 7.5,
  QuantityInTrolley: 0,
  Unit: 'Each',
  MinimumQuantity: 1,
  HasBeenBoughtBefore: false,
  IsInTrolley: false,
  Source: 'Aisle.DeliChilledMeals',
  SupplyLimit: 18,
  ProductLimit: 36,
  MaxSupplyLimitMessage: '18 item(s) left',
  IsRanged: true,
  IsInStock: true,
  PackageSize: '150G',
  IsPmDelivery: false,
  IsForCollection: true,
  IsForDelivery: true,
  IsForExpress: true,
  ProductRestrictionMessage: null,
  ProductWarningMessage: null,
  CentreTag: {
    TagContent: null,
    TagLink: null,
    FallbackText: null,
    TagType: 'None',
    MultibuyData: null,
    MemberPriceData: null,
    TagContentText: null,
    DualImageTagContent: null,
    PromotionType: 'NOT_SET',
    IsRegisteredRewardCardPromotion: false
  },
  IsCentreTag: false,
  ImageTag: {
    TagContent: null,
    TagLink: null,
    FallbackText: '',
    TagType: 'None',
    MultibuyData: null,
    MemberPriceData: null,
    TagContentText: null,
    DualImageTagContent: null,
    PromotionType: 'NOT_SET',
    IsRegisteredRewardCardPromotion: false
  },
  HeaderTag: null,
  HasHeaderTag: false,
  UnitWeightInGrams: 0,
  SupplyLimitMessage: "'Castello Blue Cheese Creamy' has a supply limit of 18. The quantity in your cart has been reduced accordingly. To purchase a larger quantity, please contact us on 1800 000 610. Please note we do not supply trade orders.",
  SmallFormatDescription: 'Castello Blue Cheese Creamy',
  FullDescription: 'Castello Blue Cheese Creamy',
  IsAvailable: true,
  InstoreIsAvailable: true,
  IsPurchasable: true,
  InstoreIsPurchasable: true,
  AgeRestricted: false,
  DisplayQuantity: 1,
  RichDescription: null,
  HideWasSavedPrice: false,
  SapCategories: null,
  Brand: 'Castello',
  IsRestrictedByDeliveryMethod: false,
  FooterTag: {
    TagContent: null,
    TagLink: null,
    FallbackText: null,
    TagType: 'None',
    MultibuyData: null,
    MemberPriceData: null,
    TagContentText: null,
    DualImageTagContent: null,
    PromotionType: 'NOT_SET',
    IsRegisteredRewardCardPromotion: false
  },
  IsFooterEnabled: false,
  Diagnostics: '71',
  IsBundle: false,
  IsInFamily: false,
  ChildProducts: null,
  UrlOverride: null,
  AdditionalAttributes: {
    boxedcontents: null,
    addedvitaminsandminerals: 'False',
    sapdepartmentname: 'FRESH CONVENIENCE',
    spf: null,
    haircolour: null,
    lifestyleanddietarystatement: 'Gluten Free,Low Sugar,Vegetarian',
    sapcategoryname: 'CHEESE ENTERTAINING',
    skintype: null,
    importantinformation: null,
    allergystatement: 'Egg Free,Fish Free,Gluten Free,Soy Free,Wheat Free',
    productdepthmm: null,
    skincondition: null,
    ophthalmologistapproved: null,
    healthstarrating: null,
    hairtype: null,
    'fragrance-free': null,
    sapsegmentname: 'BLUE',
    suitablefor: null,
    PiesProductDepartmentsjson: '[{"Id":"1_6E4F4E4","Description":"Dairy, Eggs & Fridge"},{"Id":"1_3151F6F","Description":"Deli & Chilled Meals"}]',
    piessubcategorynamesjson: '["Platters & Cheese","Entertaining Cheese","Gourmet Cheese"]',
    sapsegmentno: '8',
    productwidthmm: null,
    contains: null,
    sapsubcategoryname: 'CHEESE ENTERTAINING',
    dermatologisttested: null,
    wool_productpackaging: null,
    dermatologicallyapproved: null,
    specialsgroupid: null,
    productimages: '48824.jpg,48824_1.jpg',
    productheightmm: null,
    'r&r_hidereviews': null,
    microwavesafe: 'False',
    'paba-free': null,
    lifestyleclaim: null,
    alcoholfree: null,
    tgawarning: null,
    activeconstituents: null,
    microwaveable: 'False',
    'soap-free': null,
    countryoforigin: null,
    isexcludedfromsubstitution: 'False',
    productimagecount: '2',
    'r&r_loggedinreviews': null,
    'anti-dandruff': null,
    'servingsize-total-nip': null,
    tgahealthwarninglink: null,
    allergenmaybepresent: null,
    PiesProductDepartmentNodeId: '1_6E4F4E4',
    parabenfree: 'False',
    vendorarticleid: null,
    containsgluten: 'False',
    containsnuts: 'False',
    ingredients: 'Pasteurised Milk, Cream (Milk), Salt, Lactic Acid Culture (Milk), Microbial Rennet, Blue Mould Cultu re, Maturing Culture.',
    colour: null,
    manufacturer: null,
    sapcategoryno: '18',
    storageinstructions: 'Keep refrigerated between 0 - 5C',
    tgawarnings: null,
    piesdepartmentnamesjson: '["Dairy, Eggs & Fridge","Deli & Chilled Meals"]',
    brand: 'castello',
    oilfree: null,
    fragrance: null,
    antibacterial: 'False',
    'non-comedogenic': null,
    antiseptic: 'False',
    bpafree: 'False',
    vendorcostprice: null,
    description: "Castello Creamy Blue cheese, in its iconic half-moon shape, is a true star in Castello's portfolio. Born from trying to merge the best qualities of both brie and blue type cheeses. When maturing, it is turned 4 times in 24 hours to ensure its delicious, soft and buttery texture.<br><br>Creamy 150g half-moon of blue mould cheese<br><br>Round and milky flavour<br><br>Delicate sharpness that is not overpowering<br><br>Strength: 4 out of 6. Bold.<br><br>Creatively crafted in Denmark<br><br>Suitable for vegetarians",
    sweatresistant: null,
    sapsubcategoryno: '369',
    antioxidant: 'False',
    claims: null,
    phbalanced: null,
    wool_dietaryclaim: null,
    ophthalmologisttested: null,
    sulfatefree: 'False',
    piescategorynamesjson: '["Christmas","Cheese","Deli Specialties"]',
    'servingsperpack-total-nip': null,
    nutritionalinformation: '{"Name":"Nutritional Information","Attributes":[{"Id":705,"Name":"Carbohydrate Quantity Per 100g - Total - NIP","Value":"< 0.1g","Description":"Carbohydrate Quantity Per 100g - Total - NIP","SortOrder":83},{"Id":706,"Name":"Carbohydrate Quantity Per Serve - Total - NIP","Value":"< 0.0g","Description":"Carbohydrate Quantity Per Serve - Total - NIP","SortOrder":87},{"Id":125,"Name":"Cholesterol Quantity Per Serve - Total - NIP","Value":"30mg","Description":"Cholesterol Quantity Per Serve - Total - NIP","SortOrder":115},{"Id":759,"Name":"Energy kJ Quantity Per 100g - Total - NIP","Value":"13.2kJ","Description":"Energy kJ Quantity Per 100g - Total - NIP","SortOrder":239},{"Id":760,"Name":"Energy kJ Quantity Per Serve - Total - NIP","Value":"3.0kJ","Description":"Energy kJ Quantity Per Serve - Total - NIP","SortOrder":243},{"Id":253,"Name":"Fat Saturated Quantity Per 100g - Total - NIP","Value":"26.5g","Description":"Fat Saturated Quantity Per 100g - Total - NIP","SortOrder":251},{"Id":258,"Name":"Fat Saturated Quantity Per Serve - Total - NIP","Value":"6.6g","Description":"Fat Saturated Quantity Per Serve - Total - NIP","SortOrder":255},{"Id":764,"Name":"Fat Total Quantity Per 100g - Total - NIP","Value":"41.5g","Description":"Fat Total Quantity Per 100g - Total - NIP","SortOrder":263},{"Id":166,"Name":"Fat Total Quantity Per 100g - ValueWord - NIP","Value":"41.5","Description":"Fat Total Quantity Per 100g - ValueWord - NIP","SortOrder":264},{"Id":264,"Name":"Fat Total Quantity Per Serve - Total - NIP","Value":"10.4g","Description":"Fat Total Quantity Per Serve - Total - NIP","SortOrder":267},{"Id":834,"Name":"Monounsaturated Quantity Per Serve - Total - NIP","Value":"2.71g","Description":"Monounsaturated Quantity Per Serve - Total - NIP","SortOrder":483},{"Id":435,"Name":"Polyunsaturated Quantity Per Serve - Total - NIP","Value":"0.29g","Description":"Polyunsaturated Quantity Per Serve - Total - NIP","SortOrder":567},{"Id":493,"Name":"Potassium Quantity Per Serve - Total - NIP","Value":"26.4mg","Description":"Potassium Quantity Per Serve - Total - NIP","SortOrder":579},{"Id":878,"Name":"Protein Quantity Per 100g - Total - NIP","Value":"13.2g","Description":"Protein Quantity Per 100g - Total - NIP","SortOrder":587},{"Id":882,"Name":"Protein Quantity Per Serve - Total - NIP","Value":"3.3g","Description":"Protein Quantity Per Serve - Total - NIP","SortOrder":591},{"Id":477,"Name":"Serving Size - Total - NIP","Value":"25.0 G","Description":"Serving Size - Total - NIP","SortOrder":607},{"Id":544,"Name":"Servings Per Pack - Total - NIP","Value":"6.0","Description":"Servings Per Pack - Total - NIP","SortOrder":611},{"Id":491,"Name":"Sodium Quantity Per 100g - Total - NIP","Value":"640.0mg","Description":"Sodium Quantity Per 100g - Total - NIP","SortOrder":623},{"Id":495,"Name":"Sodium Quantity Per Serve - Total - NIP","Value":"160.0mg","Description":"Sodium Quantity Per Serve - Total - NIP","SortOrder":627},{"Id":907,"Name":"Sugars Quantity Per 100g - Prefix - NIP","Value":"<","Description":"Sugars Quantity Per 100g - Prefix - NIP","SortOrder":645},{"Id":908,"Name":"Sugars Quantity Per 100g - SuffixUnits - NIP","Value":"g","Description":"Sugars Quantity Per 100g - SuffixUnits - NIP","SortOrder":646},{"Id":909,"Name":"Sugars Quantity Per 100g - Total - NIP","Value":"< 0.1g","Description":"Sugars Quantity Per 100g - Total - NIP","SortOrder":647},{"Id":910,"Name":"Sugars Quantity Per 100g - ValueWord - NIP","Value":"0.1","Description":"Sugars Quantity Per 100g - ValueWord - NIP","SortOrder":648},{"Id":504,"Name":"Sugars Quantity Per Serve - Prefix - NIP","Value":"<","Description":"Sugars Quantity Per Serve - Prefix - NIP","SortOrder":649},{"Id":911,"Name":"Sugars Quantity Per Serve - SuffixUnits - NIP","Value":"g","Description":"Sugars Quantity Per Serve - SuffixUnits - NIP","SortOrder":650},{"Id":912,"Name":"Sugars Quantity Per Serve - Total - NIP","Value":"< 0.0g","Description":"Sugars Quantity Per Serve - Total - NIP","SortOrder":651},{"Id":572,"Name":"Sugars Quantity Per Serve - ValueWord - NIP","Value":"0.0","Description":"Sugars Quantity Per Serve - ValueWord - NIP","SortOrder":652},{"Id":510,"Name":"Trans Quantity Per Serve - Total - NIP","Value":"284.92mg","Description":"Trans Quantity Per Serve - Total - NIP","SortOrder":671}]}',
    ovencook: 'False',
    vegetarian: 'False',
    'hypo-allergenic': null,
    timer: null,
    dermatologistrecommended: null,
    sapdepartmentno: '10',
    allergencontains: 'Milk',
    waterresistant: null,
    friendlydisclaimer: null,
    recyclableinformation: null,
    usageinstructions: null,
    freezable: 'False'
  },
  DetailsImagePaths: [
    'https://cdn1.woolworths.media/content/wowproductimages/large/048824.jpg'
  ],
  Variety: 'Creamy',
  Rating: {
    ReviewCount: 0,
    RatingCount: 0,
    RatingSum: 0,
    OneStarCount: 0,
    TwoStarCount: 0,
    ThreeStarCount: 0,
    FourStarCount: 0,
    FiveStarCount: 0,
    Average: 0,
    OneStarPercentage: 0,
    TwoStarPercentage: 0,
    ThreeStarPercentage: 0,
    FourStarPercentage: 0,
    FiveStarPercentage: 0
  },
  HasProductSubs: false,
  IsSponsoredAd: false,
  AdID: null,
  AdIndex: null,
  AdStatus: null,
  IsMarketProduct: false,
  IsGiftable: false,
  Vendor: null,
  Untraceable: false,
  ThirdPartyProductInfo: null,
  MarketFeatures: null,
  MarketSpecifications: null,
  SupplyLimitSource: 'StockQuantity',
  Tags: null,
  IsPersonalisedByPurchaseHistory: false,
  IsFromFacetedSearch: false,
  NextAvailabilityDate: '2024-12-08T00:00:00.0000000Z',
  NumberOfSubstitutes: 0,
  IsPrimaryVariant: false,
  VariantGroupId: 0,
  HasVariants: false,
  VariantTitle: null,
  IsTobacco: false,
  IsB2BExtendedRangeSapCategory: false
}
