[
  {
    "Products": [
      {
        "TileID": 0,
        "Stockcode": 749588,
        "Barcode": "9339423005035",
        "GtinFormat": 13,
        "CupPrice": 0.63,
        "InstoreCupPrice": 0.63,
        "CupMeasure": "100G",
        "CupString": "$0.63 / 100G",
        "InstoreCupString": "$0.63 / 100G",
        "HasCupPrice": true,
        "InstoreHasCupPrice": true,
        "Price": 4.4,
        "InstorePrice": 4.4,
        "Name": "Tip Top The One Wholemeal Sandwich Slice Bread Loaf",
        "DisplayName": "Tip Top The One Wholemeal Sandwich Slice Bread Loaf 700g",
        "UrlFriendlyName": "tip-top-the-one-wholemeal-sandwich-slice-bread-loaf",
        "Description": " Tip Top The One Wholemeal<br>Sandwich Slice... 700g",
        "SmallImageFile": "https://cdn0.woolworths.media/content/wowproductimages/small/749588.jpg",
        "MediumImageFile": "https://cdn0.woolworths.media/content/wowproductimages/medium/749588.jpg",
        "LargeImageFile": "https://cdn0.woolworths.media/content/wowproductimages/large/749588.jpg",
        "IsNew": false,
        "IsHalfPrice": false,
        "IsOnlineOnly": false,
        "IsOnSpecial": false,
        "InstoreIsOnSpecial": false,
        "IsEdrSpecial": false,
        "SavingsAmount": 0,
        "InstoreSavingsAmount": 0,
        "WasPrice": 4.4,
        "InstoreWasPrice": 4.4,
        "QuantityInTrolley": 0,
        "Unit": "Each",
        "MinimumQuantity": 1,
        "HasBeenBoughtBefore": false,
        "IsInTrolley": false,
        "Source": "Aisle.Bakery",
        "SupplyLimit": 36,
        "ProductLimit": 36,
        "MaxSupplyLimitMessage": "36 item limit",
        "IsRanged": true,
        "IsInStock": true,
        "PackageSize": "700g",
        "IsPmDelivery": false,
        "IsForCollection": true,
        "IsForDelivery": true,
        "IsForExpress": true,
        "ProductRestrictionMessage": null,
        "ProductWarningMessage": null,
        "CentreTag": {
          "TagContent": null,
          "TagLink": null,
          "FallbackText": null,
          "TagType": "None",
          "MultibuyData": null,
          "MemberPriceData": null,
          "TagContentText": null,
          "DualImageTagContent": null,
          "PromotionType": "NOT_SET",
          "IsRegisteredRewardCardPromotion": false
        },
        "IsCentreTag": false,
        "ImageTag": {
          "TagContent": null,
          "TagLink": null,
          "FallbackText": "",
          "TagType": "None",
          "MultibuyData": null,
          "MemberPriceData": null,
          "TagContentText": null,
          "DualImageTagContent": null,
          "PromotionType": "NOT_SET",
          "IsRegisteredRewardCardPromotion": false
        },
        "HeaderTag": {
          "BackgroundColor": "#c20016",
          "BorderColor": "#c20016",
          "TextColor": "#fff",
          "Content": "LOW PRICE",
          "TagLink": null,
          "Promotion": "LowPrice"
        },
        "HasHeaderTag": true,
        "UnitWeightInGrams": 0,
        "SupplyLimitMessage": "'Tip Top The One Wholemeal Sandwich Slice Bread Loaf' has a supply limit of 36. The quantity in your cart has been reduced accordingly. To purchase a larger quantity, please contact us on 1800 000 610. Please note we do not supply trade orders.",
        "SmallFormatDescription": "Tip Top The One Wholemeal Sandwich Slice Bread Loaf",
        "FullDescription": "Tip Top The One Wholemeal Sandwich Slice Bread Loaf",
        "IsAvailable": true,
        "InstoreIsAvailable": false,
        "IsPurchasable": true,
        "InstoreIsPurchasable": false,
        "AgeRestricted": false,
        "DisplayQuantity": 1,
        "RichDescription": null,
        "HideWasSavedPrice": false,
        "SapCategories": null,
        "Brand": "Tip Top",
        "IsRestrictedByDeliveryMethod": false,
        "FooterTag": {
          "TagContent": "Lower Price Always",
          "TagLink": null,
          "FallbackText": null,
          "TagType": "Html",
          "MultibuyData": null,
          "MemberPriceData": null,
          "TagContentText": null,
          "DualImageTagContent": null,
          "PromotionType": "NOT_SET",
          "IsRegisteredRewardCardPromotion": false
        },
        "IsFooterEnabled": true,
        "Diagnostics": "72",
        "IsBundle": false,
        "IsInFamily": false,
        "ChildProducts": null,
        "UrlOverride": null,
        "AdditionalAttributes": {
          "boxedcontents": null,
          "addedvitaminsandminerals": "False",
          "sapdepartmentname": "PROPRIETARY BAKERY",
          "spf": null,
          "haircolour": null,
          "lifestyleanddietarystatement": "High Fibre",
          "sapcategoryname": "PROPRIETARY BAKERY",
          "skintype": null,
          "importantinformation": null,
          "allergystatement": "No Artificial Preservatives",
          "productdepthmm": null,
          "skincondition": null,
          "ophthalmologistapproved": null,
          "healthstarrating": "4.5",
          "hairtype": null,
          "fragrance-free": null,
          "sapsegmentname": "MULTIGRAIN/WHOLEMEAL LOAF",
          "suitablefor": "Vegans and Vegetarians",
          "PiesProductDepartmentsjson": "[{\"Id\":\"1_DEB537E\",\"Description\":\"Bakery\"},{\"Id\":\"1_9E92C35\",\"Description\":\"Lunch Box\"}]",
          "piessubcategorynamesjson": "[\"Packaged Bread\",\"Bread & Wraps\"]",
          "sapsegmentno": "4",
          "productwidthmm": null,
          "contains": null,
          "sapsubcategoryname": "RESALE BREAD",
          "dermatologisttested": null,
          "wool_productpackaging": null,
          "dermatologicallyapproved": null,
          "specialsgroupid": null,
          "productimages": "749588.jpg,749588_2.jpg,749588_3.jpg,749588_4.jpg,749588_6.jpg",
          "productheightmm": null,
          "r&r_hidereviews": null,
          "microwavesafe": "False",
          "paba-free": null,
          "lifestyleclaim": null,
          "alcoholfree": null,
          "tgawarning": null,
          "activeconstituents": null,
          "microwaveable": "False",
          "soap-free": null,
          "countryoforigin": null,
          "isexcludedfromsubstitution": "False",
          "productimagecount": "5",
          "r&r_loggedinreviews": null,
          "anti-dandruff": null,
          "servingsize-total-nip": null,
          "tgahealthwarninglink": null,
          "allergenmaybepresent": "Gluten",
          "PiesProductDepartmentNodeId": "1_DEB537E",
          "parabenfree": "False",
          "vendorarticleid": null,
          "containsgluten": "False",
          "containsnuts": "False",
          "ingredients": "Wholemeal Wheat Flour (44%), Water, Unbleached Wheat Flour, Baker's Yeast, Wheat Gluten, Wheat Fibre, Vinegar, Canola Oil, Iodised Salt, Soy Flour, Vegetable Gum (412), Vegetable Emulsifiers (472e, 481 471), Minerals (Iron, Zinc), Vitamins (Vitamin E, Niacin, Vitamin B6, Thiamin, Folic Acid).",
          "colour": null,
          "manufacturer": null,
          "sapcategoryno": "60",
          "storageinstructions": "Store in a cool, dry place away from direct sunlight.",
          "tgawarnings": null,
          "piesdepartmentnamesjson": "[\"Bakery\",\"Lunch Box\"]",
          "brand": "tip top",
          "oilfree": null,
          "fragrance": null,
          "antibacterial": "False",
          "non-comedogenic": null,
          "antiseptic": "False",
          "bpafree": "False",
          "vendorcostprice": null,
          "description": "<p>Tip Top The One Soft Wholemeal Bread 700g<br/><br/>This super soft and tasty loaf of Tip Top® The One® is high in fibre and has the added benefits of essential Vitamins and Minerals. It’s the only one you need.<br/><br/>Tip Top® is all about home-grown goodness. That's why we bake every day with Aussie wheat. We partner with Foodbank to share goodness with the community. And we use more sustainable packaging wherever we can so Australia stays beautiful for generations to come.</p>",
          "sweatresistant": null,
          "sapsubcategoryno": "950",
          "antioxidant": "False",
          "claims": null,
          "phbalanced": null,
          "wool_dietaryclaim": null,
          "ophthalmologisttested": null,
          "sulfatefree": "False",
          "servingsperpack-total-nip": null,
          "piescategorynamesjson": "[\"Packaged Bread & Bakery\",\"Lunch\"]",
          "nutritionalinformation": "{\"Name\":\"Nutritional Information\",\"Attributes\":[{\"Id\":702,\"Name\":\"Calcium Quantity Per 100g - Total - NIP\",\"Value\":\"78mg\",\"Description\":\"Calcium Quantity Per 100g - Total - NIP\",\"SortOrder\":71},{\"Id\":47,\"Name\":\"Calcium Quantity Per Serve - Total - NIP\",\"Value\":\"57.72mg\",\"Description\":\"Calcium Quantity Per Serve - Total - NIP\",\"SortOrder\":75},{\"Id\":705,\"Name\":\"Carbohydrate Quantity Per 100g - Total - NIP\",\"Value\":\"37.00g\",\"Description\":\"Carbohydrate Quantity Per 100g - Total - NIP\",\"SortOrder\":83},{\"Id\":706,\"Name\":\"Carbohydrate Quantity Per Serve - Total - NIP\",\"Value\":\"27.40g\",\"Description\":\"Carbohydrate Quantity Per Serve - Total - NIP\",\"SortOrder\":87},{\"Id\":191,\"Name\":\"Dietary Fibre Quantity Per 100g - Total - NIP\",\"Value\":\"8.50g\",\"Description\":\"Dietary Fibre Quantity Per 100g - Total - NIP\",\"SortOrder\":175},{\"Id\":120,\"Name\":\"Dietary Fibre Quantity Per Serve - Total - NIP\",\"Value\":\"6.30g\",\"Description\":\"Dietary Fibre Quantity Per Serve - Total - NIP\",\"SortOrder\":179},{\"Id\":759,\"Name\":\"Energy kJ Quantity Per 100g - Total - NIP\",\"Value\":\"977.00kJ\",\"Description\":\"Energy kJ Quantity Per 100g - Total - NIP\",\"SortOrder\":239},{\"Id\":760,\"Name\":\"Energy kJ Quantity Per Serve - Total - NIP\",\"Value\":\"723.00kJ\",\"Description\":\"Energy kJ Quantity Per Serve - Total - NIP\",\"SortOrder\":243},{\"Id\":253,\"Name\":\"Fat Saturated Quantity Per 100g - Total - NIP\",\"Value\":\"0.50g\",\"Description\":\"Fat Saturated Quantity Per 100g - Total - NIP\",\"SortOrder\":251},{\"Id\":258,\"Name\":\"Fat Saturated Quantity Per Serve - Total - NIP\",\"Value\":\"0.40g\",\"Description\":\"Fat Saturated Quantity Per Serve - Total - NIP\",\"SortOrder\":255},{\"Id\":764,\"Name\":\"Fat Total Quantity Per 100g - Total - NIP\",\"Value\":\"3.10g\",\"Description\":\"Fat Total Quantity Per 100g - Total - NIP\",\"SortOrder\":263},{\"Id\":166,\"Name\":\"Fat Total Quantity Per 100g - ValueWord - NIP\",\"Value\":\"3.10\",\"Description\":\"Fat Total Quantity Per 100g - ValueWord - NIP\",\"SortOrder\":264},{\"Id\":264,\"Name\":\"Fat Total Quantity Per Serve - Total - NIP\",\"Value\":\"2.30g\",\"Description\":\"Fat Total Quantity Per Serve - Total - NIP\",\"SortOrder\":267},{\"Id\":402,\"Name\":\"Monounsaturated Quantity Per 100g - Total - NIP\",\"Value\":null,\"Description\":\"Monounsaturated Quantity Per 100g - Total - NIP\",\"SortOrder\":479},{\"Id\":834,\"Name\":\"Monounsaturated Quantity Per Serve - Total - NIP\",\"Value\":null,\"Description\":\"Monounsaturated Quantity Per Serve - Total - NIP\",\"SortOrder\":483},{\"Id\":434,\"Name\":\"Polyunsaturated Quantity Per 100g - Total - NIP\",\"Value\":null,\"Description\":\"Polyunsaturated Quantity Per 100g - Total - NIP\",\"SortOrder\":563},{\"Id\":435,\"Name\":\"Polyunsaturated Quantity Per Serve - Total - NIP\",\"Value\":null,\"Description\":\"Polyunsaturated Quantity Per Serve - Total - NIP\",\"SortOrder\":567},{\"Id\":443,\"Name\":\"Potassium Quantity Per 100g - Total - NIP\",\"Value\":\"197mg\",\"Description\":\"Potassium Quantity Per 100g - Total - NIP\",\"SortOrder\":575},{\"Id\":493,\"Name\":\"Potassium Quantity Per Serve - Total - NIP\",\"Value\":\"145.78mg\",\"Description\":\"Potassium Quantity Per Serve - Total - NIP\",\"SortOrder\":579},{\"Id\":878,\"Name\":\"Protein Quantity Per 100g - Total - NIP\",\"Value\":\"9.70g\",\"Description\":\"Protein Quantity Per 100g - Total - NIP\",\"SortOrder\":587},{\"Id\":882,\"Name\":\"Protein Quantity Per Serve - Total - NIP\",\"Value\":\"7.20g\",\"Description\":\"Protein Quantity Per Serve - Total - NIP\",\"SortOrder\":591},{\"Id\":477,\"Name\":\"Serving Size - Total - NIP\",\"Value\":\"74.00g\",\"Description\":\"Serving Size - Total - NIP\",\"SortOrder\":607},{\"Id\":544,\"Name\":\"Servings Per Pack - Total - NIP\",\"Value\":\"9.50\",\"Description\":\"Servings Per Pack - Total - NIP\",\"SortOrder\":611},{\"Id\":491,\"Name\":\"Sodium Quantity Per 100g - Total - NIP\",\"Value\":\"380.00mg\",\"Description\":\"Sodium Quantity Per 100g - Total - NIP\",\"SortOrder\":623},{\"Id\":495,\"Name\":\"Sodium Quantity Per Serve - Total - NIP\",\"Value\":\"281.00mg\",\"Description\":\"Sodium Quantity Per Serve - Total - NIP\",\"SortOrder\":627},{\"Id\":907,\"Name\":\"Sugars Quantity Per 100g - Prefix - NIP\",\"Value\":null,\"Description\":\"Sugars Quantity Per 100g - Prefix - NIP\",\"SortOrder\":645},{\"Id\":908,\"Name\":\"Sugars Quantity Per 100g - SuffixUnits - NIP\",\"Value\":\"g\",\"Description\":\"Sugars Quantity Per 100g - SuffixUnits - NIP\",\"SortOrder\":646},{\"Id\":909,\"Name\":\"Sugars Quantity Per 100g - Total - NIP\",\"Value\":\"3.10g\",\"Description\":\"Sugars Quantity Per 100g - Total - NIP\",\"SortOrder\":647},{\"Id\":910,\"Name\":\"Sugars Quantity Per 100g - ValueWord - NIP\",\"Value\":\"3.10\",\"Description\":\"Sugars Quantity Per 100g - ValueWord - NIP\",\"SortOrder\":648},{\"Id\":504,\"Name\":\"Sugars Quantity Per Serve - Prefix - NIP\",\"Value\":null,\"Description\":\"Sugars Quantity Per Serve - Prefix - NIP\",\"SortOrder\":649},{\"Id\":911,\"Name\":\"Sugars Quantity Per Serve - SuffixUnits - NIP\",\"Value\":\"g\",\"Description\":\"Sugars Quantity Per Serve - SuffixUnits - NIP\",\"SortOrder\":650},{\"Id\":912,\"Name\":\"Sugars Quantity Per Serve - Total - NIP\",\"Value\":\"2.30g\",\"Description\":\"Sugars Quantity Per Serve - Total - NIP\",\"SortOrder\":651},{\"Id\":572,\"Name\":\"Sugars Quantity Per Serve - ValueWord - NIP\",\"Value\":\"2.30\",\"Description\":\"Sugars Quantity Per Serve - ValueWord - NIP\",\"SortOrder\":652},{\"Id\":593,\"Name\":\"Trans Quantity Per 100g - Total - NIP\",\"Value\":null,\"Description\":\"Trans Quantity Per 100g - Total - NIP\",\"SortOrder\":667},{\"Id\":510,\"Name\":\"Trans Quantity Per Serve - Total - NIP\",\"Value\":null,\"Description\":\"Trans Quantity Per Serve - Total - NIP\",\"SortOrder\":671}]}",
          "ovencook": "False",
          "vegetarian": "False",
          "hypo-allergenic": null,
          "timer": null,
          "dermatologistrecommended": null,
          "sapdepartmentno": "47",
          "allergencontains": "Gluten, Soy, Wheat",
          "waterresistant": null,
          "friendlydisclaimer": null,
          "recyclableinformation": null,
          "usageinstructions": null,
          "freezable": "False"
        },
        "DetailsImagePaths": [
          "https://cdn0.woolworths.media/content/wowproductimages/large/749588.jpg"
        ],
        "Variety": "Slice Bread Loaf",
        "Rating": {
          "ReviewCount": 0,
          "RatingCount": 0,
          "RatingSum": 0,
          "OneStarCount": 0,
          "TwoStarCount": 0,
          "ThreeStarCount": 0,
          "FourStarCount": 0,
          "FiveStarCount": 0,
          "Average": 0,
          "OneStarPercentage": 0,
          "TwoStarPercentage": 0,
          "ThreeStarPercentage": 0,
          "FourStarPercentage": 0,
          "FiveStarPercentage": 0
        },
        "HasProductSubs": false,
        "IsSponsoredAd": true,
        "AdID": "display_qIISXqCEyMGbIg0ZZM91KyK8hbEKCAoGNzQ5NTg4EgAaDAiF7--uBhDv8p6OASICCAE=",
        "AdIndex": 0,
        "IsMarketProduct": false,
        "IsGiftable": false,
        "Vendor": null,
        "Untraceable": false,
        "ThirdPartyProductInfo": null,
        "MarketFeatures": null,
        "MarketSpecifications": null,
        "SupplyLimitSource": "ProductLimit",
        "Tags": [
          {
            "Content": {
              "Type": "Label",
              "Position": "Top",
              "Attributes": {
                "Text": "LOW PRICE",
                "Promotion": "LowPrice",
                "BackgroundColor": "#c20016",
                "BorderColor": "#c20016",
                "TextColor": "#fff"
              }
            },
            "TemplateId": null,
            "Metadata": null
          }
        ],
        "IsPersonalisedByPurchaseHistory": false,
        "IsFromFacetedSearch": false,
        "NextAvailabilityDate": "2024-02-22T00:00:00.0000000Z",
        "NumberOfSubstitutes": 0,
        "IsPrimaryVariant": false,
        "VariantGroupId": 0,
        "HasVariants": false,
        "VariantTitle": null,
        "IsTobacco": false
      }
    ],
    "Name": "Tip Top The One Wholemeal Sandwich Slice Bread Loaf",
    "DisplayName": "Tip Top The One Wholemeal Sandwich Slice Bread Loaf 700g"
  },
  {
    "Products": [
      {
        "TileID": 0,
        "Stockcode": 603316,
        "Barcode": "9339423007282",
        "GtinFormat": 13,
        "CupPrice": 1.46,
        "InstoreCupPrice": 1.63,
        "CupMeasure": "100G",
        "CupString": "$1.46 / 100G",
        "InstoreCupString": "$1.63 / 100G",
        "HasCupPrice": true,
        "InstoreHasCupPrice": true,
        "Price": 3.5,
        "InstorePrice": 3.5,
        "Name": "Tip Top Sandwich Thins Original Bread Bread Low Calories & Carbs",
        "DisplayName": "Tip Top Sandwich Thins Original Bread 6 Pack",
        "UrlFriendlyName": "tip-top-sandwich-thins-original-bread-bread-low-calories-carbs",
        "Description": " Tip Top Sandwich Thins<br>Original Bread... 6 Pack",
        "SmallImageFile": "https://cdn0.woolworths.media/content/wowproductimages/small/603316.jpg",
        "MediumImageFile": "https://cdn0.woolworths.media/content/wowproductimages/medium/603316.jpg",
        "LargeImageFile": "https://cdn0.woolworths.media/content/wowproductimages/large/603316.jpg",
        "IsNew": false,
        "IsHalfPrice": false,
        "IsOnlineOnly": false,
        "IsOnSpecial": true,
        "InstoreIsOnSpecial": false,
        "IsEdrSpecial": false,
        "SavingsAmount": 0.4,
        "InstoreSavingsAmount": 0.4,
        "WasPrice": 3.9,
        "InstoreWasPrice": 3.9,
        "QuantityInTrolley": 0,
        "Unit": "Each",
        "MinimumQuantity": 1,
        "HasBeenBoughtBefore": false,
        "IsInTrolley": false,
        "Source": "Aisle.Bakery",
        "SupplyLimit": 36,
        "ProductLimit": 36,
        "MaxSupplyLimitMessage": "36 item limit",
        "IsRanged": true,
        "IsInStock": true,
        "PackageSize": "6 Pack",
        "IsPmDelivery": false,
        "IsForCollection": true,
        "IsForDelivery": true,
        "IsForExpress": true,
        "ProductRestrictionMessage": null,
        "ProductWarningMessage": null,
        "CentreTag": {
          "TagContent": null,
          "TagLink": null,
          "FallbackText": null,
          "TagType": "None",
          "MultibuyData": null,
          "MemberPriceData": null,
          "TagContentText": null,
          "DualImageTagContent": null,
          "PromotionType": "NOT_SET",
          "IsRegisteredRewardCardPromotion": false
        },
        "IsCentreTag": false,
        "ImageTag": {
          "TagContent": "/content/promotiontags/roundel-special-200x200.png",
          "TagLink": "",
          "FallbackText": "On Special",
          "TagType": "None",
          "MultibuyData": null,
          "MemberPriceData": null,
          "TagContentText": null,
          "DualImageTagContent": null,
          "PromotionType": "NOT_SET",
          "IsRegisteredRewardCardPromotion": false
        },
        "HeaderTag": {
          "BackgroundColor": "#fd0",
          "BorderColor": "#fd0",
          "TextColor": "#000",
          "Content": "Save $0.40",
          "TagLink": null,
          "Promotion": "Special"
        },
        "HasHeaderTag": true,
        "UnitWeightInGrams": 0,
        "SupplyLimitMessage": "'Tip Top Sandwich Thins Original Bread Bread Low Calories & Carbs' has a supply limit of 36. The quantity in your cart has been reduced accordingly. To purchase a larger quantity, please contact us on 1800 000 610. Please note we do not supply trade orders.",
        "SmallFormatDescription": "Tip Top Sandwich Thins Original Bread Bread Low Calories & Carbs",
        "FullDescription": "Tip Top Sandwich Thins Original Bread Bread Low Calories & Carbs",
        "IsAvailable": true,
        "InstoreIsAvailable": false,
        "IsPurchasable": true,
        "InstoreIsPurchasable": false,
        "AgeRestricted": false,
        "DisplayQuantity": 1,
        "RichDescription": null,
        "HideWasSavedPrice": false,
        "SapCategories": null,
        "Brand": "Tip Top",
        "IsRestrictedByDeliveryMethod": false,
        "FooterTag": {
          "TagContent": null,
          "TagLink": null,
          "FallbackText": null,
          "TagType": "None",
          "MultibuyData": null,
          "MemberPriceData": null,
          "TagContentText": null,
          "DualImageTagContent": null,
          "PromotionType": "NOT_SET",
          "IsRegisteredRewardCardPromotion": false
        },
        "IsFooterEnabled": false,
        "Diagnostics": "73",
        "IsBundle": false,
        "IsInFamily": false,
        "ChildProducts": null,
        "UrlOverride": null,
        "AdditionalAttributes": {
          "boxedcontents": null,
          "addedvitaminsandminerals": "False",
          "sapdepartmentname": "PROPRIETARY BAKERY",
          "spf": null,
          "haircolour": null,
          "lifestyleanddietarystatement": "Source of Fibre",
          "sapcategoryname": "PROPRIETARY BAKERY",
          "skintype": null,
          "importantinformation": null,
          "allergystatement": "Fish Free",
          "productdepthmm": null,
          "skincondition": null,
          "ophthalmologistapproved": null,
          "healthstarrating": "4",
          "hairtype": null,
          "fragrance-free": null,
          "sapsegmentname": "WRAPS",
          "suitablefor": null,
          "PiesProductDepartmentsjson": "[{\"Id\":\"1_DEB537E\",\"Description\":\"Bakery\"},{\"Id\":\"1_9E92C35\",\"Description\":\"Lunch Box\"}]",
          "piessubcategorynamesjson": "[\"Wraps & Flatbread\",\"Bread & Wraps\"]",
          "sapsegmentno": "1",
          "productwidthmm": null,
          "contains": null,
          "sapsubcategoryname": "RESALE INTERNATIONAL BREAD",
          "dermatologisttested": null,
          "wool_productpackaging": null,
          "dermatologicallyapproved": null,
          "specialsgroupid": null,
          "productimages": "603316.jpg,603316_2.jpg,603316_3.jpg",
          "productheightmm": null,
          "r&r_hidereviews": null,
          "microwavesafe": "False",
          "paba-free": null,
          "lifestyleclaim": null,
          "alcoholfree": null,
          "tgawarning": null,
          "activeconstituents": null,
          "microwaveable": "False",
          "soap-free": null,
          "countryoforigin": null,
          "isexcludedfromsubstitution": "False",
          "productimagecount": "3",
          "r&r_loggedinreviews": null,
          "anti-dandruff": null,
          "servingsize-total-nip": null,
          "tgahealthwarninglink": null,
          "allergenmaybepresent": "Sesame",
          "PiesProductDepartmentNodeId": "1_DEB537E",
          "parabenfree": "False",
          "vendorarticleid": null,
          "containsgluten": "False",
          "containsnuts": "False",
          "ingredients": "Wheat Flour, Wholegrain Wholemeal Wheat Flour (32%), Water, Baker's Yeast, Vinegar, Wheat Gluten, Canola Oil, Dextrose, Iodised Salt, Sugar, Soy Flour, Fermented Wheat Flour, Vegetable Emulsifiers (481, 471, 472e), Vegetable Gums (466, 415), Vitamins (Thiamin, Folic Acid), Processing Aid (Wheat).",
          "colour": null,
          "manufacturer": null,
          "sapcategoryno": "60",
          "storageinstructions": "Store in a cool, dry place away from direct sunlight. See Best Before date on pack. Freezing not recommended.",
          "tgawarnings": null,
          "piesdepartmentnamesjson": "[\"Bakery\",\"Lunch Box\"]",
          "brand": "tip top",
          "oilfree": null,
          "fragrance": null,
          "antibacterial": "False",
          "non-comedogenic": null,
          "antiseptic": "False",
          "bpafree": "False",
          "vendorcostprice": null,
          "description": "Top it, Toast it, Fill it or Grill it!<br><br>Try Tip Top Thins with eggs for breakfast, a quick snack with banana and ricotta or as a mini pizza base. They're so delicious… in so many ways!<br><br>SOURCE OF FIBRE<br><br>25% OF YOUR WHOLE GRAIN DAILY INTAKE<br><br>4 Star Health Rating<br><br>No Artificial Colours, Flavours or Preservatives<br><br>FODMAP Friendly<br><br>105 Calories per serving",
          "sweatresistant": null,
          "sapsubcategoryno": "810",
          "antioxidant": "False",
          "claims": null,
          "phbalanced": null,
          "wool_dietaryclaim": null,
          "ophthalmologisttested": null,
          "sulfatefree": "False",
          "servingsperpack-total-nip": null,
          "piescategorynamesjson": "[\"Packaged Bread & Bakery\",\"Lunch\"]",
          "nutritionalinformation": "{\"Name\":\"Nutritional Information\",\"Attributes\":[{\"Id\":702,\"Name\":\"Calcium Quantity Per 100g - Total - NIP\",\"Value\":\"57mg\",\"Description\":\"Calcium Quantity Per 100g - Total - NIP\",\"SortOrder\":71},{\"Id\":705,\"Name\":\"Carbohydrate Quantity Per 100g - Total - NIP\",\"Value\":\"44.60g\",\"Description\":\"Carbohydrate Quantity Per 100g - Total - NIP\",\"SortOrder\":83},{\"Id\":706,\"Name\":\"Carbohydrate Quantity Per Serve - Total - NIP\",\"Value\":\"17.80g\",\"Description\":\"Carbohydrate Quantity Per Serve - Total - NIP\",\"SortOrder\":87},{\"Id\":191,\"Name\":\"Dietary Fibre Quantity Per 100g - Total - NIP\",\"Value\":\"6.00g\",\"Description\":\"Dietary Fibre Quantity Per 100g - Total - NIP\",\"SortOrder\":175},{\"Id\":120,\"Name\":\"Dietary Fibre Quantity Per Serve - Total - NIP\",\"Value\":\"2.40g\",\"Description\":\"Dietary Fibre Quantity Per Serve - Total - NIP\",\"SortOrder\":179},{\"Id\":759,\"Name\":\"Energy kJ Quantity Per 100g - Total - NIP\",\"Value\":\"1100.00kJ\",\"Description\":\"Energy kJ Quantity Per 100g - Total - NIP\",\"SortOrder\":239},{\"Id\":760,\"Name\":\"Energy kJ Quantity Per Serve - Total - NIP\",\"Value\":\"440.00kJ\",\"Description\":\"Energy kJ Quantity Per Serve - Total - NIP\",\"SortOrder\":243},{\"Id\":253,\"Name\":\"Fat Saturated Quantity Per 100g - Total - NIP\",\"Value\":\"0.50g\",\"Description\":\"Fat Saturated Quantity Per 100g - Total - NIP\",\"SortOrder\":251},{\"Id\":258,\"Name\":\"Fat Saturated Quantity Per Serve - Total - NIP\",\"Value\":\"0.20g\",\"Description\":\"Fat Saturated Quantity Per Serve - Total - NIP\",\"SortOrder\":255},{\"Id\":764,\"Name\":\"Fat Total Quantity Per 100g - Total - NIP\",\"Value\":\"3.10g\",\"Description\":\"Fat Total Quantity Per 100g - Total - NIP\",\"SortOrder\":263},{\"Id\":166,\"Name\":\"Fat Total Quantity Per 100g - ValueWord - NIP\",\"Value\":\"3.10\",\"Description\":\"Fat Total Quantity Per 100g - ValueWord - NIP\",\"SortOrder\":264},{\"Id\":264,\"Name\":\"Fat Total Quantity Per Serve - Total - NIP\",\"Value\":\"1.20g\",\"Description\":\"Fat Total Quantity Per Serve - Total - NIP\",\"SortOrder\":267},{\"Id\":402,\"Name\":\"Monounsaturated Quantity Per 100g - Total - NIP\",\"Value\":\"0.63g\",\"Description\":\"Monounsaturated Quantity Per 100g - Total - NIP\",\"SortOrder\":479},{\"Id\":434,\"Name\":\"Polyunsaturated Quantity Per 100g - Total - NIP\",\"Value\":\"0.66g\",\"Description\":\"Polyunsaturated Quantity Per 100g - Total - NIP\",\"SortOrder\":563},{\"Id\":443,\"Name\":\"Potassium Quantity Per 100g - Total - NIP\",\"Value\":\"120mg\",\"Description\":\"Potassium Quantity Per 100g - Total - NIP\",\"SortOrder\":575},{\"Id\":878,\"Name\":\"Protein Quantity Per 100g - Total - NIP\",\"Value\":\"9.50g\",\"Description\":\"Protein Quantity Per 100g - Total - NIP\",\"SortOrder\":587},{\"Id\":882,\"Name\":\"Protein Quantity Per Serve - Total - NIP\",\"Value\":\"3.80g\",\"Description\":\"Protein Quantity Per Serve - Total - NIP\",\"SortOrder\":591},{\"Id\":477,\"Name\":\"Serving Size - Total - NIP\",\"Value\":\"40.00g\",\"Description\":\"Serving Size - Total - NIP\",\"SortOrder\":607},{\"Id\":544,\"Name\":\"Servings Per Pack - Total - NIP\",\"Value\":\"6.00\",\"Description\":\"Servings Per Pack - Total - NIP\",\"SortOrder\":611},{\"Id\":491,\"Name\":\"Sodium Quantity Per 100g - Total - NIP\",\"Value\":\"360.00mg\",\"Description\":\"Sodium Quantity Per 100g - Total - NIP\",\"SortOrder\":623},{\"Id\":495,\"Name\":\"Sodium Quantity Per Serve - Total - NIP\",\"Value\":\"144.00mg\",\"Description\":\"Sodium Quantity Per Serve - Total - NIP\",\"SortOrder\":627},{\"Id\":907,\"Name\":\"Sugars Quantity Per 100g - Prefix - NIP\",\"Value\":null,\"Description\":\"Sugars Quantity Per 100g - Prefix - NIP\",\"SortOrder\":645},{\"Id\":908,\"Name\":\"Sugars Quantity Per 100g - SuffixUnits - NIP\",\"Value\":\"g\",\"Description\":\"Sugars Quantity Per 100g - SuffixUnits - NIP\",\"SortOrder\":646},{\"Id\":909,\"Name\":\"Sugars Quantity Per 100g - Total - NIP\",\"Value\":\"3.90g\",\"Description\":\"Sugars Quantity Per 100g - Total - NIP\",\"SortOrder\":647},{\"Id\":910,\"Name\":\"Sugars Quantity Per 100g - ValueWord - NIP\",\"Value\":\"3.90\",\"Description\":\"Sugars Quantity Per 100g - ValueWord - NIP\",\"SortOrder\":648},{\"Id\":504,\"Name\":\"Sugars Quantity Per Serve - Prefix - NIP\",\"Value\":null,\"Description\":\"Sugars Quantity Per Serve - Prefix - NIP\",\"SortOrder\":649},{\"Id\":911,\"Name\":\"Sugars Quantity Per Serve - SuffixUnits - NIP\",\"Value\":\"g\",\"Description\":\"Sugars Quantity Per Serve - SuffixUnits - NIP\",\"SortOrder\":650},{\"Id\":912,\"Name\":\"Sugars Quantity Per Serve - Total - NIP\",\"Value\":\"1.60g\",\"Description\":\"Sugars Quantity Per Serve - Total - NIP\",\"SortOrder\":651},{\"Id\":572,\"Name\":\"Sugars Quantity Per Serve - ValueWord - NIP\",\"Value\":\"1.60\",\"Description\":\"Sugars Quantity Per Serve - ValueWord - NIP\",\"SortOrder\":652},{\"Id\":593,\"Name\":\"Trans Quantity Per 100g - Total - NIP\",\"Value\":\"17.3mg\",\"Description\":\"Trans Quantity Per 100g - Total - NIP\",\"SortOrder\":667}]}",
          "ovencook": "False",
          "vegetarian": "False",
          "hypo-allergenic": null,
          "timer": null,
          "dermatologistrecommended": null,
          "sapdepartmentno": "47",
          "allergencontains": "Wheat, Soy, Gluten",
          "waterresistant": null,
          "friendlydisclaimer": null,
          "recyclableinformation": null,
          "usageinstructions": null,
          "freezable": "False"
        },
        "DetailsImagePaths": [
          "https://cdn0.woolworths.media/content/wowproductimages/large/603316.jpg"
        ],
        "Variety": "Bread Low Calories & Carbs",
        "Rating": {
          "ReviewCount": 0,
          "RatingCount": 0,
          "RatingSum": 0,
          "OneStarCount": 0,
          "TwoStarCount": 0,
          "ThreeStarCount": 0,
          "FourStarCount": 0,
          "FiveStarCount": 0,
          "Average": 0,
          "OneStarPercentage": 0,
          "TwoStarPercentage": 0,
          "ThreeStarPercentage": 0,
          "FourStarPercentage": 0,
          "FiveStarPercentage": 0
        },
        "HasProductSubs": false,
        "IsSponsoredAd": true,
        "AdID": "display_aCIzjGGs51lYJKaYqy3pM3RlmvgKCAoGNjAzMzE2EgAaDAiF7--uBhDQ_qCOASICCAE=",
        "AdIndex": 1,
        "IsMarketProduct": false,
        "IsGiftable": false,
        "Vendor": null,
        "Untraceable": false,
        "ThirdPartyProductInfo": null,
        "MarketFeatures": null,
        "MarketSpecifications": null,
        "SupplyLimitSource": "ProductLimit",
        "Tags": [
          {
            "Content": {
              "Type": "Label",
              "Position": "Top",
              "Attributes": {
                "Text": "Save $0.40",
                "Promotion": "Special",
                "BackgroundColor": "#fd0",
                "BorderColor": "#fd0",
                "TextColor": "#000"
              }
            },
            "TemplateId": null,
            "Metadata": null
          },
          {
            "Content": {
              "Type": "Roundel",
              "Position": "Top",
              "Attributes": {
                "ImagePath": "/content/promotiontags/roundel-special-200x200.png",
                "FallbackText": "On Special"
              }
            },
            "TemplateId": null,
            "Metadata": null
          }
        ],
        "IsPersonalisedByPurchaseHistory": false,
        "IsFromFacetedSearch": false,
        "NextAvailabilityDate": "2024-02-22T00:00:00.0000000Z",
        "NumberOfSubstitutes": 0,
        "IsPrimaryVariant": false,
        "VariantGroupId": 0,
        "HasVariants": false,
        "VariantTitle": null,
        "IsTobacco": false
      }
    ],
    "Name": "Tip Top Sandwich Thins Original Bread Bread Low Calories & Carbs",
    "DisplayName": "Tip Top Sandwich Thins Original Bread 6 Pack"
  }

]